name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install eigen3
      run: apt-get install libeigen3-dev
    - name: install boost
      run: apt-get install libboost-all-dev
    - name: configure
      run: mkdir build && cd build && cmake -DCMAKE_CXX_FLAGS="-Wall -Werror" ..
    - name: make
      run: cd build && make
    - name: make check
      run: cd build && ctest -V
